version: '2'
services:
    tresorerie-app:
        image: tresorerie
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tresorerie-mysql:3306/tresorerie?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8082:8082
    tresorerie-mysql:
        extends:
            file: mysql.yml
            service: tresorerie-mysql
